title: "Zach Maddox"
description: "Software Engineering, Java, Cloud, and Architecture"
theme: jekyll-theme-minimal

# Enable Jekyll posts
plugins:
  - jekyll-feed

# Where posts will live
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: site
      author: "Zach Maddox"
