title: "Zach Maddox"
description: "Software Engineering, Java, Cloud, and Architecture"
theme: jekyll-theme-minimal
url: "https://zachmaddox.dev"

# Enable Jekyll posts
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Where posts will live
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: post
      author: "Zach Maddox"
